// import ClientOrServer from '@/components/ClientOrServer'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'

//SSR

// import ClientOrServer from "@/components/ClientOrServer";

//ONLY client-side
/* import dynamic from 'next/dynamic'
const ClientOrServer = dynamic(
  () => import("@/components/ClientOrServer"),
  { ssr : false}
) 
export default function Home() {
  return <ClientOrServer/>
}
*/
export default function Home() {
  const router = useRouter()
  const onBtnProjectsClick = () => {
    router.push({
      pathname : '/projects'
    })
  }
  const onBtnCustomersClick = () => {
    router.push({
      pathname : '/customers'
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>My Next App</h1>
      {/* <a href="/projects">Projects</a> */}
     {/*  
     <Link href="/projects" prefetch={false} >Projects</Link>
      <Link href="/customers" prefetch={false} >Customers</Link> 
      */}
      <button onClick={onBtnProjectsClick}>Projects</button>
      <button onClick={onBtnCustomersClick}>Customers</button>
    </>
  ) 

}
